package middleware

var notificationPingValid = `
{
      "zen": "Encourage flow.",
      "hook_id": 11169236,
      "hook": {
        "type": "Repository",
        "id": 11169236,
        "name": "web",
        "active": true,
        "events": [
          "pull_request",
          "push"
        ],
        "config": {
          "content_type": "json",
          "insecure_ssl": "0",
          "url": "http://gnampfelix.de:8080/notification"
        },
        "updated_at": "2016-12-15T18:00:00Z",
        "created_at": "2016-12-15T18:00:00Z",
        "url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236",
        "test_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236/test",
        "ping_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236/pings",
        "last_response": {
          "code": null,
          "status": "unused",
          "message": null
        }
      },
      "repository": {
        "id": 76581419,
        "name": "gnampfelix-ci-tests",
        "full_name": "Thamtham/gnampfelix-ci-tests",
        "owner": {
          "login": "Thamtham",
          "id": 10077533,
          "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Thamtham",
          "html_url": "https://github.com/Thamtham",
          "followers_url": "https://api.github.com/users/Thamtham/followers",
          "following_url": "https://api.github.com/users/Thamtham/following{/other_user}",
          "gists_url": "https://api.github.com/users/Thamtham/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Thamtham/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Thamtham/subscriptions",
          "organizations_url": "https://api.github.com/users/Thamtham/orgs",
          "repos_url": "https://api.github.com/users/Thamtham/repos",
          "events_url": "https://api.github.com/users/Thamtham/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Thamtham/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": true,
        "html_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests",
        "forks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/forks",
        "keys_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/teams",
        "hooks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks",
        "issue_events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/events",
        "assignees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/tags",
        "blobs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/languages",
        "stargazers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/stargazers",
        "contributors_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contributors",
        "subscribers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscribers",
        "subscription_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscription",
        "commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/merges",
        "archive_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/downloads",
        "issues_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/labels{/name}",
        "releases_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/deployments",
        "created_at": "2016-12-15T17:32:39Z",
        "updated_at": "2016-12-15T17:32:39Z",
        "pushed_at": "2016-12-15T17:32:41Z",
        "git_url": "git://github.com/Thamtham/gnampfelix-ci-tests.git",
        "ssh_url": "git@github.com:Thamtham/gnampfelix-ci-tests.git",
        "clone_url": "https://github.com/Thamtham/gnampfelix-ci-tests.git",
        "svn_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
        "homepage": null,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      },
      "sender": {
        "login": "Thamtham",
        "id": 10077533,
        "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Thamtham",
        "html_url": "https://github.com/Thamtham",
        "followers_url": "https://api.github.com/users/Thamtham/followers",
        "following_url": "https://api.github.com/users/Thamtham/following{/other_user}",
        "gists_url": "https://api.github.com/users/Thamtham/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Thamtham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Thamtham/subscriptions",
        "organizations_url": "https://api.github.com/users/Thamtham/orgs",
        "repos_url": "https://api.github.com/users/Thamtham/repos",
        "events_url": "https://api.github.com/users/Thamtham/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Thamtham/received_events",
        "type": "User",
        "site_admin": false
      }
    }
`

var notificationPingValidInvalidConfig = `
{
      "zen": "Encourage flow.",
      "hook_id": 11169236,
      "hook": {
        "type": "Repository",
        "id": 11169236,
        "name": "web",
        "active": true,
        "events": [
          "pull_request",
          "push"
        ],
        "config": {
          "content_type": "json",
          "insecure_ssl": "0",
          "url": "http://gnampfelix.de:8080/notification"
        },
        "updated_at": "2016-12-15T18:00:00Z",
        "created_at": "2016-12-15T18:00:00Z",
        "url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236",
        "test_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236/test",
        "ping_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236/pings",
        "last_response": {
          "code": null,
          "status": "unused",
          "message": null
        }
      },
      "repository": {
        "id": 76581419,
        "name": "rolap",
        "full_name": "Thamtham/rolap",
        "owner": {
          "login": "Thamtham",
          "id": 10077533,
          "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Thamtham",
          "html_url": "https://github.com/Thamtham",
          "followers_url": "https://api.github.com/users/Thamtham/followers",
          "following_url": "https://api.github.com/users/Thamtham/following{/other_user}",
          "gists_url": "https://api.github.com/users/Thamtham/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Thamtham/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Thamtham/subscriptions",
          "organizations_url": "https://api.github.com/users/Thamtham/orgs",
          "repos_url": "https://api.github.com/users/Thamtham/repos",
          "events_url": "https://api.github.com/users/Thamtham/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Thamtham/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": true,
        "html_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests",
        "forks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/forks",
        "keys_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/teams",
        "hooks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks",
        "issue_events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/events",
        "assignees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/tags",
        "blobs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/languages",
        "stargazers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/stargazers",
        "contributors_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contributors",
        "subscribers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscribers",
        "subscription_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscription",
        "commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/merges",
        "archive_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/downloads",
        "issues_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/labels{/name}",
        "releases_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/deployments",
        "created_at": "2016-12-15T17:32:39Z",
        "updated_at": "2016-12-15T17:32:39Z",
        "pushed_at": "2016-12-15T17:32:41Z",
        "git_url": "git://github.com/Thamtham/gnampfelix-ci-tests.git",
        "ssh_url": "git@github.com:Thamtham/gnampfelix-ci-tests.git",
        "clone_url": "https://github.com/Thamtham/gnampfelix-ci-tests.git",
        "svn_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
        "homepage": null,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      },
      "sender": {
        "login": "Thamtham",
        "id": 10077533,
        "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Thamtham",
        "html_url": "https://github.com/Thamtham",
        "followers_url": "https://api.github.com/users/Thamtham/followers",
        "following_url": "https://api.github.com/users/Thamtham/following{/other_user}",
        "gists_url": "https://api.github.com/users/Thamtham/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Thamtham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Thamtham/subscriptions",
        "organizations_url": "https://api.github.com/users/Thamtham/orgs",
        "repos_url": "https://api.github.com/users/Thamtham/repos",
        "events_url": "https://api.github.com/users/Thamtham/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Thamtham/received_events",
        "type": "User",
        "site_admin": false
      }
    }
`

var notificationPingInvalid = `
{
      "zen": "Encourage flow.",
      "hook_id": 11169236,
      "hook": {
        "type": "Repository",
        "id": 11169236,
        "name": "web",
        "active": true,
        "events": [
          "pull_request",
          "push"
        ],
        "config": {
          "content_type": "json",
          "insecure_ssl": "0",
          "url": "http://gnampfelix.de:8080/notification"
        },
        "updated_at": "2016-12-15T18:00:00Z",
        "created_at": "2016-12-15T18:00:00Z",
        "url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236",
        "test_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236/test",
        "ping_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks/11169236/pings",
        "last_response": {
          "code": null,
          "status": "unused",
          "message": null
        }
      },
        "private": true,
        "html_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests",
        "forks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/forks",
        "keys_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/teams",
        "hooks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks",
        "issue_events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/events",
        "assignees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/tags",
        "blobs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/languages",
        "stargazers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/stargazers",
        "contributors_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contributors",
        "subscribers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscribers",
        "subscription_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscription",
        "commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/merges",
        "archive_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/downloads",
        "issues_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/labels{/name}",
        "releases_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/deployments",
        "created_at": "2016-12-15T17:32:39Z",
        "updated_at": "2016-12-15T17:32:39Z",
        "pushed_at": "2016-12-15T17:32:41Z",
        "git_url": "git://github.com/Thamtham/gnampfelix-ci-tests.git",
        "ssh_url": "git@github.com:Thamtham/gnampfelix-ci-tests.git",
        "clone_url": "https://github.com/Thamtham/gnampfelix-ci-tests.git",
        "svn_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
        "homepage": null,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      },
      "sender": {
        "login": "Thamtham",
        "id": 10077533,
        "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Thamtham",
        "html_url": "https://github.com/Thamtham",
        "followers_url": "https://api.github.com/users/Thamtham/followers",
        "following_url": "https://api.github.com/users/Thamtham/following{/other_user}",
        "gists_url": "https://api.github.com/users/Thamtham/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Thamtham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Thamtham/subscriptions",
        "organizations_url": "https://api.github.com/users/Thamtham/orgs",
        "repos_url": "https://api.github.com/users/Thamtham/repos",
        "events_url": "https://api.github.com/users/Thamtham/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Thamtham/received_events",
        "type": "User",
        "site_admin": false
      }
    }
`
var notificationPushValid = `
{
  "ref": "refs/heads/master",
  "before": "778fa27e2259b995db4b78cb4fa58e28873a26fe",
  "after": "22d235c9ca5f84a6b332645a8612eec8e363cd30",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/Thamtham/gnampfelix-ci-tests/compare/778fa27e2259...22d235c9ca5f",
  "commits": [
    {
      "id": "22d235c9ca5f84a6b332645a8612eec8e363cd30",
      "tree_id": "65b5b78c78d6530fa6f661cc68cc3a5e9ab0c0b3",
      "distinct": true,
      "message": "Update Readme.md",
      "timestamp": "2016-12-15T19:13:12+01:00",
      "url": "https://github.com/Thamtham/gnampfelix-ci-tests/commit/22d235c9ca5f84a6b332645a8612eec8e363cd30",
      "author": {
        "name": "Felix S",
        "email": "feli-x-seidel@gmx.de",
        "username": "Thamtham"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "README.md"
      ]
    }
  ],
  "head_commit": {
    "id": "22d235c9ca5f84a6b332645a8612eec8e363cd30",
    "tree_id": "65b5b78c78d6530fa6f661cc68cc3a5e9ab0c0b3",
    "distinct": true,
    "message": "Update Readme.md",
    "timestamp": "2016-12-15T19:13:12+01:00",
    "url": "https://github.com/Thamtham/gnampfelix-ci-tests/commit/22d235c9ca5f84a6b332645a8612eec8e363cd30",
    "author": {
      "name": "Felix S",
      "email": "feli-x-seidel@gmx.de",
      "username": "Thamtham"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "README.md"
    ]
  },
  "repository": {
    "id": 76581419,
    "name": "gnampfelix-ci-tests",
    "full_name": "Thamtham/gnampfelix-ci-tests",
    "owner": {
      "name": "Thamtham",
      "email": "feli-x-seidel@gmx.de"
    },
    "private": true,
    "html_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
    "description": null,
    "fork": false,
    "url": "https://github.com/Thamtham/gnampfelix-ci-tests",
    "forks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/forks",
    "keys_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/teams",
    "hooks_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/hooks",
    "issue_events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/events",
    "assignees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/tags",
    "blobs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/languages",
    "stargazers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/stargazers",
    "contributors_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contributors",
    "subscribers_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscribers",
    "subscription_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/subscription",
    "commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/merges",
    "archive_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/downloads",
    "issues_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/labels{/name}",
    "releases_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Thamtham/gnampfelix-ci-tests/deployments",
    "created_at": 1481823159,
    "updated_at": "2016-12-15T17:32:39Z",
    "pushed_at": 1481825592,
    "git_url": "git://github.com/Thamtham/gnampfelix-ci-tests.git",
    "ssh_url": "git@github.com:Thamtham/gnampfelix-ci-tests.git",
    "clone_url": "https://github.com/Thamtham/gnampfelix-ci-tests.git",
    "svn_url": "https://github.com/Thamtham/gnampfelix-ci-tests",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "Thamtham",
    "email": "feli-x-seidel@gmx.de"
  },
  "sender": {
    "login": "Thamtham",
    "id": 10077533,
    "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Thamtham",
    "html_url": "https://github.com/Thamtham",
    "followers_url": "https://api.github.com/users/Thamtham/followers",
    "following_url": "https://api.github.com/users/Thamtham/following{/other_user}",
    "gists_url": "https://api.github.com/users/Thamtham/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Thamtham/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Thamtham/subscriptions",
    "organizations_url": "https://api.github.com/users/Thamtham/orgs",
    "repos_url": "https://api.github.com/users/Thamtham/repos",
    "events_url": "https://api.github.com/users/Thamtham/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Thamtham/received_events",
    "type": "User",
    "site_admin": false
  }
}
`

var notificationPullRequestValid = `{
  "action": "opened",
  "number": 2,
  "pull_request": {
    "url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/2",
    "id": 106139458,
    "html_url": "https://github.com/gnampfelix/gnampfelix-ci-tests/pull/2",
    "diff_url": "https://github.com/gnampfelix/gnampfelix-ci-tests/pull/2.diff",
    "patch_url": "https://github.com/gnampfelix/gnampfelix-ci-tests/pull/2.patch",
    "issue_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/2",
    "number": 2,
    "state": "open",
    "locked": false,
    "title": "Add another headline",
    "user": {
      "login": "gnampfelix",
      "id": 10077533,
      "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gnampfelix",
      "html_url": "https://github.com/gnampfelix",
      "followers_url": "https://api.github.com/users/gnampfelix/followers",
      "following_url": "https://api.github.com/users/gnampfelix/following{/other_user}",
      "gists_url": "https://api.github.com/users/gnampfelix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gnampfelix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gnampfelix/subscriptions",
      "organizations_url": "https://api.github.com/users/gnampfelix/orgs",
      "repos_url": "https://api.github.com/users/gnampfelix/repos",
      "events_url": "https://api.github.com/users/gnampfelix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gnampfelix/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "Catch me if you can",
    "created_at": "2017-02-14T16:22:12Z",
    "updated_at": "2017-02-14T16:22:12Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "commits_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/2/commits",
    "review_comments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/2/comments",
    "review_comment_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/2/comments",
    "statuses_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/statuses/fa27ba8fe0f4f174b7d3a8e4d1e505ba267f768b",
    "head": {
      "label": "gnampfelix:testBranch",
      "ref": "testBranch",
      "sha": "fa27ba8fe0f4f174b7d3a8e4d1e505ba267f768b",
      "user": {
        "login": "gnampfelix",
        "id": 10077533,
        "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gnampfelix",
        "html_url": "https://github.com/gnampfelix",
        "followers_url": "https://api.github.com/users/gnampfelix/followers",
        "following_url": "https://api.github.com/users/gnampfelix/following{/other_user}",
        "gists_url": "https://api.github.com/users/gnampfelix/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gnampfelix/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gnampfelix/subscriptions",
        "organizations_url": "https://api.github.com/users/gnampfelix/orgs",
        "repos_url": "https://api.github.com/users/gnampfelix/repos",
        "events_url": "https://api.github.com/users/gnampfelix/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gnampfelix/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 76581419,
        "name": "gnampfelix-ci-tests",
        "full_name": "gnampfelix/gnampfelix-ci-tests",
        "owner": {
          "login": "gnampfelix",
          "id": 10077533,
          "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/gnampfelix",
          "html_url": "https://github.com/gnampfelix",
          "followers_url": "https://api.github.com/users/gnampfelix/followers",
          "following_url": "https://api.github.com/users/gnampfelix/following{/other_user}",
          "gists_url": "https://api.github.com/users/gnampfelix/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/gnampfelix/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/gnampfelix/subscriptions",
          "organizations_url": "https://api.github.com/users/gnampfelix/orgs",
          "repos_url": "https://api.github.com/users/gnampfelix/repos",
          "events_url": "https://api.github.com/users/gnampfelix/events{/privacy}",
          "received_events_url": "https://api.github.com/users/gnampfelix/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": true,
        "html_url": "https://github.com/gnampfelix/gnampfelix-ci-tests",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests",
        "forks_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/forks",
        "keys_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/teams",
        "hooks_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/hooks",
        "issue_events_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/events{/number}",
        "events_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/events",
        "assignees_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/assignees{/user}",
        "branches_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/branches{/branch}",
        "tags_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/tags",
        "blobs_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/languages",
        "stargazers_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/stargazers",
        "contributors_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/contributors",
        "subscribers_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/subscribers",
        "subscription_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/subscription",
        "commits_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/contents/{+path}",
        "compare_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/merges",
        "archive_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/downloads",
        "issues_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues{/number}",
        "pulls_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/labels{/name}",
        "releases_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/releases{/id}",
        "deployments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/deployments",
        "created_at": "2016-12-15T17:32:39Z",
        "updated_at": "2016-12-18T13:07:24Z",
        "pushed_at": "2017-02-14T16:16:38Z",
        "git_url": "git://github.com/gnampfelix/gnampfelix-ci-tests.git",
        "ssh_url": "git@github.com:gnampfelix/gnampfelix-ci-tests.git",
        "clone_url": "https://github.com/gnampfelix/gnampfelix-ci-tests.git",
        "svn_url": "https://github.com/gnampfelix/gnampfelix-ci-tests",
        "homepage": null,
        "size": 3,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Go",
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 1,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "base": {
      "label": "gnampfelix:master",
      "ref": "master",
      "sha": "a018910516ce3996dad52e7db6902661f787bdd6",
      "user": {
        "login": "gnampfelix",
        "id": 10077533,
        "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gnampfelix",
        "html_url": "https://github.com/gnampfelix",
        "followers_url": "https://api.github.com/users/gnampfelix/followers",
        "following_url": "https://api.github.com/users/gnampfelix/following{/other_user}",
        "gists_url": "https://api.github.com/users/gnampfelix/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gnampfelix/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gnampfelix/subscriptions",
        "organizations_url": "https://api.github.com/users/gnampfelix/orgs",
        "repos_url": "https://api.github.com/users/gnampfelix/repos",
        "events_url": "https://api.github.com/users/gnampfelix/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gnampfelix/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 76581419,
        "name": "gnampfelix-ci-tests",
        "full_name": "gnampfelix/gnampfelix-ci-tests",
        "owner": {
          "login": "gnampfelix",
          "id": 10077533,
          "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/gnampfelix",
          "html_url": "https://github.com/gnampfelix",
          "followers_url": "https://api.github.com/users/gnampfelix/followers",
          "following_url": "https://api.github.com/users/gnampfelix/following{/other_user}",
          "gists_url": "https://api.github.com/users/gnampfelix/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/gnampfelix/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/gnampfelix/subscriptions",
          "organizations_url": "https://api.github.com/users/gnampfelix/orgs",
          "repos_url": "https://api.github.com/users/gnampfelix/repos",
          "events_url": "https://api.github.com/users/gnampfelix/events{/privacy}",
          "received_events_url": "https://api.github.com/users/gnampfelix/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": true,
        "html_url": "https://github.com/gnampfelix/gnampfelix-ci-tests",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests",
        "forks_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/forks",
        "keys_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/teams",
        "hooks_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/hooks",
        "issue_events_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/events{/number}",
        "events_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/events",
        "assignees_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/assignees{/user}",
        "branches_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/branches{/branch}",
        "tags_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/tags",
        "blobs_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/languages",
        "stargazers_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/stargazers",
        "contributors_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/contributors",
        "subscribers_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/subscribers",
        "subscription_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/subscription",
        "commits_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/contents/{+path}",
        "compare_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/merges",
        "archive_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/downloads",
        "issues_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues{/number}",
        "pulls_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/labels{/name}",
        "releases_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/releases{/id}",
        "deployments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/deployments",
        "created_at": "2016-12-15T17:32:39Z",
        "updated_at": "2016-12-18T13:07:24Z",
        "pushed_at": "2017-02-14T16:16:38Z",
        "git_url": "git://github.com/gnampfelix/gnampfelix-ci-tests.git",
        "ssh_url": "git@github.com:gnampfelix/gnampfelix-ci-tests.git",
        "clone_url": "https://github.com/gnampfelix/gnampfelix-ci-tests.git",
        "svn_url": "https://github.com/gnampfelix/gnampfelix-ci-tests",
        "homepage": null,
        "size": 3,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Go",
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 1,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/2"
      },
      "html": {
        "href": "https://github.com/gnampfelix/gnampfelix-ci-tests/pull/2"
      },
      "issue": {
        "href": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/2"
      },
      "comments": {
        "href": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/2/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/2/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls/2/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/statuses/fa27ba8fe0f4f174b7d3a8e4d1e505ba267f768b"
      }
    },
    "requested_reviewers": [

    ],
    "merged": false,
    "mergeable": null,
    "mergeable_state": "unknown",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 1,
    "deletions": 1,
    "changed_files": 1
  },
  "repository": {
    "id": 76581419,
    "name": "gnampfelix-ci-tests",
    "full_name": "gnampfelix/gnampfelix-ci-tests",
    "owner": {
      "login": "gnampfelix",
      "id": 10077533,
      "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gnampfelix",
      "html_url": "https://github.com/gnampfelix",
      "followers_url": "https://api.github.com/users/gnampfelix/followers",
      "following_url": "https://api.github.com/users/gnampfelix/following{/other_user}",
      "gists_url": "https://api.github.com/users/gnampfelix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gnampfelix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gnampfelix/subscriptions",
      "organizations_url": "https://api.github.com/users/gnampfelix/orgs",
      "repos_url": "https://api.github.com/users/gnampfelix/repos",
      "events_url": "https://api.github.com/users/gnampfelix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gnampfelix/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": true,
    "html_url": "https://github.com/gnampfelix/gnampfelix-ci-tests",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests",
    "forks_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/forks",
    "keys_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/teams",
    "hooks_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/hooks",
    "issue_events_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/events{/number}",
    "events_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/events",
    "assignees_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/assignees{/user}",
    "branches_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/branches{/branch}",
    "tags_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/tags",
    "blobs_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/languages",
    "stargazers_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/stargazers",
    "contributors_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/contributors",
    "subscribers_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/subscribers",
    "subscription_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/subscription",
    "commits_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/contents/{+path}",
    "compare_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/merges",
    "archive_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/downloads",
    "issues_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/issues{/number}",
    "pulls_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/labels{/name}",
    "releases_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/releases{/id}",
    "deployments_url": "https://api.github.com/repos/gnampfelix/gnampfelix-ci-tests/deployments",
    "created_at": "2016-12-15T17:32:39Z",
    "updated_at": "2016-12-18T13:07:24Z",
    "pushed_at": "2017-02-14T16:16:38Z",
    "git_url": "git://github.com/gnampfelix/gnampfelix-ci-tests.git",
    "ssh_url": "git@github.com:gnampfelix/gnampfelix-ci-tests.git",
    "clone_url": "https://github.com/gnampfelix/gnampfelix-ci-tests.git",
    "svn_url": "https://github.com/gnampfelix/gnampfelix-ci-tests",
    "homepage": null,
    "size": 3,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Go",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 1,
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "gnampfelix",
    "id": 10077533,
    "avatar_url": "https://avatars.githubusercontent.com/u/10077533?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gnampfelix",
    "html_url": "https://github.com/gnampfelix",
    "followers_url": "https://api.github.com/users/gnampfelix/followers",
    "following_url": "https://api.github.com/users/gnampfelix/following{/other_user}",
    "gists_url": "https://api.github.com/users/gnampfelix/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gnampfelix/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gnampfelix/subscriptions",
    "organizations_url": "https://api.github.com/users/gnampfelix/orgs",
    "repos_url": "https://api.github.com/users/gnampfelix/repos",
    "events_url": "https://api.github.com/users/gnampfelix/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gnampfelix/received_events",
    "type": "User",
    "site_admin": false
  }
}`

var validConfigFile = `
{
    "actions": {
        "push":[
        {
            "Branches": ["master"],
            "PreTest": "pre.sh",
            "Test": "test.sh"
        }
        ],
        "pull_request":[
        {
            "Branches": ["master"],
            "PreTest": "pre.sh",
            "Test": "test.sh"
        }
        ]
    },
    "User": "Thamtham",
    "Token": "774b7670bb68f364c182f0a2094821b6cd646331"
}
`
